# Init schema

# --- !Ups

create table SPRINT (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  TITLE varchar(255) NOT NULL,
  NUM int(10) NOT NULL,
  SPRINTSTART date NOT NULL,
  SPRINTEND date NOT NULL,
  COUNTERSJSON varchar(1000) NOT NULL,
  PRIMARY KEY (id)
);

create table STORY (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  TAG varchar(50) NOT NULL,
  DESCRIPTION varchar(1000) NOT NULL,
  POINTS int(10) NOT NULL,
  SPRINTID bigint(20) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (SPRINTID) REFERENCES SPRINT(ID)
);

create table DAYCOUNT (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  DAYNUM int(10) NOT NULL,
  COUNTERVALUESJSON varchar(1000) NOT NULL,
  SPRINTID bigint(20) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (SPRINTID) REFERENCES SPRINT(ID)
);

create unique index IDX_DAYCOUNT_DAYNUM on DAYCOUNT(SPRINTID, DAYNUM);

create table DISPLAY (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  NAME varchar(255) NOT NULL,
  SPRINTID bigint(20) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (SPRINTID) REFERENCES SPRINT(ID)
);

create table DISPLAYITEM (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  DISPLAYID bigint(20) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (DISPLAYID) REFERENCES DISPLAY(ID)
);

# --- !Downs

drop table DISPLAYITEM;

drop table DISPLAY;

drop table DAYCOUNT;

drop table STORY;

drop table SPRINT;