# --- !Ups

alter table DISPLAYITEM ADD CONSTRAINT FK_DISPLAYITEM_PROJECT FOREIGN KEY (PROJECTID) REFERENCES PROJECT(ID);
alter table DISPLAYITEM ADD CONSTRAINT FK_DISPLAYITEM_TEAM FOREIGN KEY (TEAMID) REFERENCES TEAM(ID);
alter table DISPLAY ADD CONSTRAINT FK_DISPLAY_PROJECT FOREIGN KEY (PROJECTID) REFERENCES PROJECT(ID);
alter table DISPLAY ADD CONSTRAINT FK_DISPLAY_TEAM FOREIGN KEY (TEAMID) REFERENCES TEAM(ID);
alter table SPRINT ADD CONSTRAINT FK_SPRINT_TEAM FOREIGN KEY (TEAMID) REFERENCES TEAM(ID);

# --- !Downs

alter table SPRINT DROP CONSTRAINT FK_SPRINT_TEAM;
alter table DISPLAY DROP CONSTRAINT FK_DISPLAY_PROJECT;
alter table DISPLAY DROP CONSTRAINT FK_DISPLAY_TEAM;
alter table DISPLAYITEM DROP CONSTRAINT FK_DISPLAYITEM_TEAM;
alter table DISPLAYITEM DROP CONSTRAINT FK_DISPLAYITEM_PROJECT;
